# Generated by Django 6.0.2 on 2026-02-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(fields=('title', 'category', 'author'), name='unique_book_per_category_author'),
        ),
    ]
